<?php

/**
 * @file
 * Contains ng2_entity module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function ng2_entity_theme() {
  return [
    'angular2_component' => [
      'variables' => [
        'entity' => NULL,
        'component' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_view().
 */
function ng2_entity_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Invoke hookEntityView() method from "ng2_entity.ng2_view_display" service.
  \Drupal::service('ng2_entity.ng2_view_display')
    ->hookEntityView($build, $entity, $display, $view_mode);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ng2_entity_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state) {
  // Invoke hookFormEntityViewDisplayEditAlter() method from "ng2_entity.ng2_view_display" service.
  \Drupal::service('ng2_entity.ng2_view_display')
    ->hookFormEntityViewDisplayEditAlter($form, $form_state);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ng2_entity_preprocess_angular2_component(&$variables) {
  // Invoke hookPreprocessAngular2Component() method from "ng2_entity.ng2_view_display" service.
  \Drupal::service('ng2_entity.ng2_view_display')
    ->hookPreprocessAngular2Component($variables);
}
